default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: quitando_development
  demo:
    <<: *default
    url: <%= ENV["DEMO_DATABASE_URL"] %>
    database: quitando_demo_development
    migrations_paths: db/migrate
    schema_dump: structure.sql

test:
  primary:
    <<: *default
    url: <%= ENV["TEST_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    database: quitando_test
  demo:
    <<: *default
    url: <%= ENV["DEMO_TEST_DATABASE_URL"] %>
    database: quitando_demo_test
    migrations_paths: db/migrate
    schema_dump: structure.sql

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: quitando_production
    username: quitando
    password: <%= ENV["QUITANDO_DATABASE_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
  cache:
    <<: *primary_production
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    database: quitando_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    database: quitando_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    database: quitando_production_cable
    migrations_paths: db/cable_migrate
